logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  rabbitmq:
    host: 192.168.233.100
    port: 5672
    username: user
    password: password
    virtual-host: /
    listener:
      simple:
        prefetch: 1